Collections:
- Metadata:
    Architecture:
    - HRNetv2
    - UDP
  Name: hrnetv2_udp_rhd2d
  Paper:
  - https://ieeexplore.ieee.org/abstract/document/9052469/
  - http://openaccess.thecvf.com/content_CVPR_2020/html/Huang_The_Devil_Is_in_the_Details_Delving_Into_Unbiased_Data_CVPR_2020_paper.html
  - https://lmb.informatik.uni-freiburg.de/projects/hand3d/
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_udp_rhd2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_w18_rhd2d_256x256_udp.py
  In Collection: hrnetv2_udp_rhd2d
  Metadata:
    Training Data: RHD
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--rhd2d--hrnetv2_w18_rhd2d_256x256_udp
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.742
      EPE: 7.84
      PCKh@0.7: 0.998
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_rhd2d_256x256_udp-63ba6007_20210330.pth
