Collections:
- Name: UDP
  Paper:
    Title: 'The Devil Is in the Details: Delving Into Unbiased Data Processing for
      Human Pose Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Huang_The_Devil_Is_in_the_Details_Delving_Into_Unbiased_Data_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/udp.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_w18_rhd2d_256x256_udp.py
  In Collection: UDP
  Metadata:
    Architecture:
    - HRNetv2
    - UDP
    Training Data: RHD
  Name: topdown_heatmap_hrnetv2_w18_rhd2d_256x256_udp
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.902
      EPE: 2.21
      PCKh@0.7: 0.992
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_rhd2d_256x256_udp-63ba6007_20210330.pth
