image: registry.sensetime.com/eig-research/pytorch:1.3.1-cuda10.1-cudnn7-devel

stages:
    - linting
    - test
    - deploy

before_script:
  - echo $PATH
  - gcc --version
  - python --version
  - pip --version
  - nvcc --version
  - nvidia-smi
  - python -c "import torch; print(torch.__version__)"

linting:
  stage: linting
  script:
    - pip install flake8 yapf isort==4.3.21
    - flake8 .
    - isort -rc --check-only --diff mmpose/ tools/ tests/
    - yapf -r -d mmpose/ tools/ tests/ configs/

test:
  stage: test
  script:
    - echo "Start building..."
    - pip install pillow==6.2.2
    - pip install scipy
    - pip install json_tricks
    - pip install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
    - pip install -e .
    - python -c "import mmpose; print(mmpose.__version__)"
    - echo "Start testing..."
    - pip install pytest coverage
    - coverage run --branch --source mmpose -m pytest tests/
    - coverage report -m

pages:
  stage: deploy
  script:
    - pip install mmcv
    - pip install sphinx sphinx_rtd_theme recommonmark sphinx-markdown-tables matplotlib pillow==6.2.2 scipy json_tricks pycocotools
    - pip install -e .
    - cd docs
    - make html
    - cd ..
    - mkdir -p ./public
    - cp -r docs/_build/html/* ./public
    - ls ./public
  artifacts:
    paths:
      - public
  only:
    - master
