Collections:
- Name: CPM
  Paper:
    Title: Convolutional pose machines
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/Wei_Convolutional_Pose_Machines_CVPR_2016_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/cpm.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub1_368x368.py
  In Collection: CPM
  Metadata:
    Architecture: &id001
    - CPM
    Training Data: JHMDB
  Name: topdown_heatmap_cpm_jhmdb_sub1_368x368
  Results:
  - Dataset: JHMDB
    Metrics:
      Ank: 87.3
      Elb: 81.0
      Head: 96.1
      Hip: 96.6
      Knee: 90.8
      Mean: 89.5
      Sho: 91.9
      Wri: 78.9
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub1_368x368-2d2585c9_20201122.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub2_368x368.py
  In Collection: CPM
  Metadata:
    Architecture: *id001
    Training Data: JHMDB
  Name: topdown_heatmap_cpm_jhmdb_sub2_368x368
  Results:
  - Dataset: JHMDB
    Metrics:
      Ank: 84.7
      Elb: 77.1
      Head: 98.1
      Hip: 94.0
      Knee: 89.1
      Mean: 87.4
      Sho: 93.6
      Wri: 70.9
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub2_368x368-fc742f1f_20201122.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub3_368x368.py
  In Collection: CPM
  Metadata:
    Architecture: *id001
    Training Data: JHMDB
  Name: topdown_heatmap_cpm_jhmdb_sub3_368x368
  Results:
  - Dataset: JHMDB
    Metrics:
      Ank: 86.2
      Elb: 87.3
      Head: 97.9
      Hip: 98.6
      Knee: 94.4
      Mean: 92.4
      Sho: 94.9
      Wri: 84.0
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub3_368x368-49337155_20201122.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub1_368x368.py
  In Collection: CPM
  Metadata:
    Architecture: *id001
    Training Data: JHMDB
  Name: topdown_heatmap_cpm_jhmdb_sub1_368x368
  Results:
  - Dataset: JHMDB
    Metrics:
      Ank: 61.2
      Elb: 54.0
      Head: 89.0
      Hip: 68.2
      Knee: 63.1
      Mean: 66.0
      Sho: 63.0
      Wri: 54.9
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub1_368x368-2d2585c9_20201122.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub2_368x368.py
  In Collection: CPM
  Metadata:
    Architecture: *id001
    Training Data: JHMDB
  Name: topdown_heatmap_cpm_jhmdb_sub2_368x368
  Results:
  - Dataset: JHMDB
    Metrics:
      Ank: 62.4
      Elb: 46.8
      Head: 90.3
      Hip: 60.8
      Knee: 58.2
      Mean: 61.1
      Sho: 57.9
      Wri: 44.3
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub2_368x368-fc742f1f_20201122.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub3_368x368.py
  In Collection: CPM
  Metadata:
    Architecture: *id001
    Training Data: JHMDB
  Name: topdown_heatmap_cpm_jhmdb_sub3_368x368
  Results:
  - Dataset: JHMDB
    Metrics:
      Ank: 65.8
      Elb: 59.9
      Head: 91.0
      Hip: 73.2
      Knee: 68.5
      Mean: 70.3
      Sho: 72.6
      Wri: 54.0
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub3_368x368-49337155_20201122.pth
