Collections:
- Metadata:
    Architecture:
    - ViPNAS
    - DarkPose
  Name: wholebody--2d_kpt_sview_rgb_img--topdown_heatmap--coco-wholebody--vipnas_dark_coco-wholebody
    [ViPNAS+DarkPose@COCO-WholeBody]
  Paper:
    Title: 'ViPNAS: Efficient Video Pose Estimation via Neural Architecture Search'
    URL: https://arxiv.org/abs/2105.10154
  README: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_dark_coco-wholebody.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_res50_coco_wholebody_256x192_dark.py
  In Collection: wholebody--2d_kpt_sview_rgb_img--topdown_heatmap--coco-wholebody--vipnas_dark_coco-wholebody
    [ViPNAS+DarkPose@COCO-WholeBody]
  Metadata:
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_vipnas_res50_coco_wholebody_256x192_dark
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.65
      Body AR: 0.732
      Face AP: 0.684
      Face AR: 0.784
      Foot AP: 0.55
      Foot AR: 0.686
      Hand AP: 0.437
      Hand AR: 0.554
      Whole AP: 0.528
      Whole AR: 0.632
    Task: Wholebody 2D Keypoint
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmpose/top_down/vipnas/vipnas_res50_wholebody_256x192_dark-67c0ce35_20211112.pth
