Collections:
  - Name: PoseResNet
    Metadata:
      Training Techniques:
        - Adam
      Architecture:
        - ResNet
    Paper:
      - https://arxiv.org/abs/1804.06208
      - https://arxiv.org/abs/1710.03740
    README: configs/top_down/resnet/README.md

Models:
  - Name: res50_coco_256x192
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res50_coco_256x192.py
    Metadata:
      Training Data: COCO
      FLOPs: 5460000000
      Parameters: 34000000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.718
          AP50: 0.898
          AP75: 0.795
          AR: 0.773
          AR50: 0.937
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192-ec54d7f3_20200709.pth

  - Name: res50_coco_384x288
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res50_coco_384x288.py
    Metadata:
      Training Data: COCO
      FLOPs: 12290000000
      Parameters: 34000000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.731
          AP50: 0.900
          AP75: 0.799
          AR: 0.783
          AR50: 0.931
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_384x288-e6f795e9_20200709.pth

  - Name: res101_coco_256x192
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res101_coco_256x192.py
    Metadata:
      Training Data: COCO
      FLOPs: 9110000000
      Parameters: 52990000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.726
          AP50: 0.899
          AP75: 0.806
          AR: 0.781
          AR50: 0.939
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_256x192-6e6babf0_20200708.pth

  - Name: res101_coco_384x288
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res101_coco_384x288.py
    Metadata:
      Training Data: COCO
      FLOPs: 20500000000
      Parameters: 52990000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.748
          AP50: 0.905
          AP75: 0.817
          AR: 0.798
          AR50: 0.940
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_coco_384x288-8c71bdc9_20200709.pth

  - Name: res152_coco_256x192
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res152_coco_256x192.py
    Metadata:
      Training Data: COCO
      FLOPs: 12770000000
      Parameters: 68640000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.735
          AP50: 0.905
          AP75: 0.812
          AR: 0.790
          AR50: 0.943
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_256x192-f6e307c2_20200709.pth

  - Name: res152_coco_384x288
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res152_coco_384x288.py
    Metadata:
      Training Data: COCO
      FLOPs: 28730000000
      Parameters: 68640000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.750
          AP50: 0.908
          AP75: 0.821
          AR: 0.800
          AR50: 0.942
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_coco_384x288-3860d4c9_20200709.pth

  - Name: res50_coco_256x192_fp16_dynamic
    In Collection: PoseResNet
    Config: configs/top_down/resnet/coco/res50_coco_256x192_fp16_dynamic.py
    Metadata:
      Training Data: COCO
      FLOPs: 5460000000
      Parameters: 34000000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.717
          AP50: 0.898
          AP75: 0.793
          AR: 0.772
          AR50: 0.936
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192_fp16_dynamic-6edb79f3_20210430.pth

  - Name: res50_mpii_256x256
    In Collection: PoseResNet
    Config: configs/top_down/resnet/mpii/res50_mpii_256x256.py
    Metadata:
      Training Data: MPII
      FLOPs: 7280000000
      Parameters: 34000000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: MPII
        Metrics:
          Mean: 0.882
          Mean@0.1: 0.286
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mpii_256x256-418ffc88_20200812.pth

  - Name: res101_mpii_256x256
    In Collection: PoseResNet
    Config: configs/top_down/resnet/mpii/res101_mpii_256x256.py
    Metadata:
      Training Data: MPII
      FLOPs: 12150000000
      Parameters: 52990000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: MPII
        Metrics:
          Mean: 0.888
          Mean@0.1: 0.290
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_mpii_256x256-416f5d71_20200812.pth

  - Name: res152_mpii_256x256
    In Collection: PoseResNet
    Config: configs/top_down/resnet/mpii/res152_mpii_256x256.py
    Metadata:
      Training Data: MPII
      FLOPs: 17020000000
      Parameters: 68640000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: MPII
        Metrics:
          Mean: 0.889
          Mean@0.1: 0.303
    Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_mpii_256x256-3ecba29d_20200812.pth
