Collections:
- Name: Wingloss
  Paper:
    Title: Wing Loss for Robust Facial Landmark Localisation with Convolutional Neural
      Networks
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Feng_Wing_Loss_for_CVPR_2018_paper.html
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/res50_wflw_256x256_wingloss.py
  In Collection: Wingloss
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
    - Wingloss
    Training Data: WFLW
  Name: deeppose_res50_wflw_256x256_wingloss
  README: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/resnet_wingloss_wflw.md
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 5.26
      NME expression: 5.07
      NME illumination: 4.59
      NME makeup: 4.59
      NME occlusion: 5.56
      NME pose: 8.25
      NME test: 4.64
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/deeppose/deeppose_res50_wflw_256x256_wingloss-f82a5e53_20210303.pth
