blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/open-mmlab/mmpose/discussions
    about: Ask general questions and discuss with other MMPose community members
  - name: ğŸ“˜ MMPose Documentation
    url: https://mmpose.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
  - name: ğŸŒ Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get to know more about OpenMMLab
