Models:
- Config: configs/hand_2d_keypoint/rtmpose/coco_wholebody_hand/rtmpose-m_8xb32-210e_coco-wholebody-hand-256x256.py
  In Collection: RTMPose
  Alias: hand
  Metadata:
    Architecture:
    - RTMPose
    Training Data: COCO-WholeBody-Hand
  Name: rtmpose-m_8xb32-210e_coco-wholebody-hand-256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.815
      EPE: 4.51
      PCK@0.2: 0.837
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-coco-wholebody-hand_pt-aic-coco_210e-256x256-99477206_20230228.pth
