Collections:
- Name: SimpleBaseline3D
  Paper:
    Title: A simple yet effective baseline for 3d human pose estimation
    URL: http://openaccess.thecvf.com/content_iccv_2017/html/Martinez_A_Simple_yet_ICCV_2017_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline3d.md
Models:
- Config: configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.py
  In Collection: SimpleBaseline3D
  Metadata:
    Architecture:
    - SimpleBaseline3D
    Training Data: MPI-INF-3DHP
  Name: pose_lift_simplebaseline3d_mpi-inf-3dhp
  Results:
  - Dataset: MPI-INF-3DHP
    Metrics:
      3DAUC: 52.0
      3DPCK: 85.0
      MPJPE: 84.3
      P-MPJPE: 53.2
    Task: Body 3D Keypoint
  Weights: https://download.openmmlab.com/mmpose/body3d/simple_baseline/simplebaseline3d_mpi-inf-3dhp-b75546f6_20210603.pth
