Collections:
- Name: SCNet
  Paper:
    Title: Improving Convolutional Networks with Self-Calibrated Convolutions
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Liu_Improving_Convolutional_Networks_With_Self-Calibrated_Convolutions_CVPR_2020_paper.html
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/scnet50_coco_wholebody_face_256x256.py
  In Collection: SCNet
  Metadata:
    Architecture:
    - SCNet
    Training Data: COCO-WholeBody-Face
  Name: topdown_heatmap_scnet50_coco_wholebody_face_256x256
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/scnet_coco_wholebody_face.md
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0565
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/scnet/scnet50_coco_wholebody_face_256x256-a0183f5f_20210909.pth
