Collections:
- Name: DarkPose
  Paper:
    Title: Distribution-aware coordinate representation for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/techniques/dark.md
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/halpe/hrnet_w48_halpe_384x288_dark_plus.py
  In Collection: DarkPose
  Metadata:
    Architecture:
    - HRNet
    - DarkPose
    Training Data: Halpe
  Name: topdown_heatmap_hrnet_w48_halpe_384x288_dark_plus
  Results:
  - Dataset: Halpe
    Metrics:
      Whole AP: 0.527
      Whole AR: 0.62
    Task: Wholebody 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_halpe_384x288_dark_plus-d13c2588_20211021.pth
