Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/hrnet_w32_ap10k_256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: AP-10K
  Name: topdown_heatmap_hrnet_w32_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.722
      AP@0.5: 0.939
      AP@0.75: 0.787
      APL: 0.73
      APM: 0.555
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_ap10k_256x256-18aac840_20211029.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/hrnet_w48_ap10k_256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AP-10K
  Name: topdown_heatmap_hrnet_w48_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.731
      AP@0.5: 0.937
      AP@0.75: 0.804
      APL: 0.738
      APM: 0.574
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_ap10k_256x256-d95ab412_20211029.pth
