Collections:
- Name: SimpleBaseline2D
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/simplebaseline2d.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/res50_ap10k_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    Training Data: AP-10K
  Name: topdown_heatmap_res50_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.681
      AP@0.5: 0.923
      AP@0.75: 0.74
      APL: 0.688
      APM: 0.51
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_ap10k_256x256-35760eb8_20211029.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/res101_ap10k_256x256.py
  In Collection: SimpleBaseline2D
  Metadata:
    Architecture: *id001
    Training Data: AP-10K
  Name: topdown_heatmap_res101_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.681
      AP@0.5: 0.922
      AP@0.75: 0.742
      APL: 0.688
      APM: 0.534
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_ap10k_256x256-9edfafb9_20211029.pth
