Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--ap10k--resnet_ap10k [SimpleBaseline2D@AP-10K]
  Paper:
    Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/resnet_ap10k.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/res50_ap10k_256x256.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--ap10k--resnet_ap10k
    [SimpleBaseline2D@AP-10K]
  Metadata:
    Training Data: AP-10K
  Name: topdown_heatmap_res50_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.699
      AP@0.5: 0.94
      AP@0.75: 0.76
      APL: 0.703
      APM: 0.57
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_ap10k_256x256-35760eb8_20211029.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/res101_ap10k_256x256.py
  In Collection: animal--2d_kpt_sview_rgb_img--topdown_heatmap--ap10k--resnet_ap10k
    [SimpleBaseline2D@AP-10K]
  Metadata:
    Training Data: AP-10K
  Name: topdown_heatmap_res101_ap10k_256x256
  Results:
  - Dataset: AP-10K
    Metrics:
      AP: 0.698
      AP@0.5: 0.943
      AP@0.75: 0.754
      APL: 0.702
      APM: 0.543
    Task: Animal 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_ap10k_256x256-9edfafb9_20211029.pth
