Collections:
- Name: HRNet
  Paper:
    Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/hrnet.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_fp16_dynamic.py
  In Collection: HRNet
  Metadata:
    Architecture:
    - HRNet
    Training Data: COCO
  Name: topdown_heatmap_hrnet_w32_coco_256x192_fp16_dynamic
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.905
      AP@0.75: 0.88
      AR: 0.8
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192_fp16_dynamic-290efc2e_20210430.pth
