Collections:
- Name: RTMO
  Paper:
    Title: 'RTMO: Towards High-Performance One-Stage Real-Time Multi-Person Pose Estimation'
    URL: https://arxiv.org/abs/2204.06806  # TODO: update the url
  README: https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/algorithms/yolopose.md  # TODO: update the paper
Models:
- Config: configs/body_2d_keypoint/rtmo/body7/rtmo-s_8xb32-600e_body7-640x640.py
  In Collection: RTMO
  Metadata:
    Architecture: &id001
    - RTMO
    Training Data: &id002
    - AI Challenger
    - COCO
    - CrowdPose
    - MPII
    - sub-JHMDB
    - Halpe
    - PoseTrack18
  Name: rtmo-s_8xb32-600e_body7-640x640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.686
      AP@0.5: 0.879
      AP@0.75: 0.744
      AR: 0.723
      AR@0.5: 0.908
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-s_8xb32-600e_body7-640x640-dac2bf74_20231211.pth
- Config: configs/body_2d_keypoint/rtmo/body7/rtmo-m_16xb16-600e_body7-640x640.py
  In Collection: RTMO
  Metadata:
    Architecture: *id001
    Training Data: *id002
  Name: rtmo-m_16xb16-600e_body7-640x640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.726
      AP@0.5: 0.899
      AP@0.75: 0.790
      AR: 0.763
      AR@0.5: 0.926
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-m_16xb16-600e_body7-640x640-39e78cc4_20231211.pth
- Config: configs/body_2d_keypoint/rtmo/body7/rtmo-l_16xb16-600e_body7-640x640.py
  In Collection: RTMO
  Alias: rtmo
  Metadata:
    Architecture: *id001
    Training Data: *id002
  Name: rtmo-l_16xb16-600e_body7-640x640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.748
      AP@0.5: 0.911
      AP@0.75: 0.813
      AR: 0.786
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-l_16xb16-600e_body7-640x640-516a421f_20231211.pth
